- name: "Disabling switchport"
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ item.name }}"
        mode: layer3
  loop: "{{  l3_interfaces  }}"

- name: "Adding ipv4 address"
  cisco.ios.ios_l3_interfaces:
    config:
      - name: "{{ item.name }}"
        ipv4:
          - address:  "{{ item.address }}/{{ item.mask }}"
  loop: "{{  l3_interfaces  }}"